POST http://localhost:8080/api/v1/companies
Content-Type: application/json

{
  "name": "Test Company",
  "shipping_address": "123 Test St, Nowheresville, NZ 1234",
  "billing_address": "123 Test St, Nowheresville, NZ 1234",
  "phone": "123-456-7890",
  "email": "test.company@email.com",
  "primary_contact_id": 1,
  "notes": "This is a test company for the db"
}